<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuiteCore.Domain\SuiteCore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Auth\" />
    <Folder Include="DTOs\Users\" />
    <Folder Include="Interfaces\Infrastructure\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
